import type { ConnectorKey, DealerRecord, DealerSourceConfig } from "./types";

function source(
  key: string,
  name: string,
  startUrl: string | null,
  connectorKey: ConnectorKey,
  options: {
    required?: boolean;
    dedicated?: boolean;
    notes?: string;
    preferBrowser?: boolean;
    headed?: boolean;
    waitForSelector?: string;
    settleMs?: number;
    maxPages?: number;
  } = {},
): DealerSourceConfig {
  return {
    key,
    name,
    startUrl,
    connectorKey,
    required: options.required ?? Boolean(startUrl),
    dedicated: options.dedicated ?? true,
    notes: options.notes,
    preferBrowser: options.preferBrowser,
    headed: options.headed,
    waitForSelector: options.waitForSelector,
    settleMs: options.settleMs,
    maxPages: options.maxPages,
  };
}

function dealer(record: DealerRecord): DealerRecord {
  return record;
}

export const DEALER_REGISTRY: readonly DealerRecord[] = [
  dealer({
    key: "athol-garage",
    displayName: "Athol Garage",
    status: "confirmed",
    website: "https://www.athol.im/",
    stockUrls: ["https://www.athol.im/used-cars/"],
    platformHint: "NetDirector",
    connectorKey: "netdirector",
    groupKey: null,
    locations: ["Ballasalla"],
    sources: [
      source("used-cars", "Athol used cars", "https://www.athol.im/used-cars/", "netdirector"),
    ],
    notes: "Research identified NetDirector. Prove reusable connector via config, not an Athol branch.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "automann",
    displayName: "AutoMann",
    status: "no_public_site",
    website: null,
    stockUrls: [],
    platformHint: null,
    connectorKey: "csv",
    groupKey: null,
    locations: [],
    sources: [source("csv", "CSV/manual", null, "csv", { required: false })],
    notes: "No standalone dealer website found. CSV/managed feed only.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "bcc-cars",
    displayName: "BCC Cars",
    status: "confirmed",
    website: "https://www.bcccars.im/",
    stockUrls: ["https://www.bcccars.im/used-cars/"],
    platformHint: "Autoweb",
    connectorKey: "autoweb",
    groupKey: null,
    locations: ["Kirk Michael"],
    sources: [source("used-cars", "BCC used cars", "https://www.bcccars.im/used-cars/", "autoweb")],
    notes: "Live Autoweb used-cars list confirmed 2026-08-22.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "bespoke-vehicle-sales",
    displayName: "Bespoke Vehicle Sales",
    status: "confirmed",
    website: "https://www.bespokegroup.im/",
    stockUrls: [
      "https://www.bespokegroup.im/cars-for-sale",
      "https://www.reynolds.im/used-cars/",
    ],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: "bespoke",
    locations: [],
    sources: [
      source(
        "bespoke",
        "Bespoke used cars",
        "https://www.bespokegroup.im/cars-for-sale",
        "html-structured",
      ),
      source("reynolds", "Reynolds", null, "html-structured", {
        dedicated: false,
        required: false,
        notes: "reynolds.im/used-cars fatals. Not a live public list.",
      }),
    ],
    notes: "Official list is bespokegroup.im/cars-for-sale. Reynolds used-cars URL fatals.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "best-cars",
    displayName: "Best Cars",
    status: "confirmed",
    website: "https://www.bestcars.im/",
    stockUrls: ["https://www.bestcars.im/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Best Cars stock", "https://www.bestcars.im/", "html-structured")],
    notes: "Inspect live stock implementation during probe.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "bettridge-motors",
    displayName: "Bettridge Motors",
    status: "confirmed",
    website: "https://www.bettridges.com/",
    stockUrls: ["https://www.bettridges.com/motor/"],
    platformHint: "Scorch",
    connectorKey: "html-structured",
    groupKey: null,
    locations: ["Foxdale"],
    sources: [
      source("used-cars", "Bettridge used cars", "https://www.bettridges.com/motor/", "html-structured", {
        preferBrowser: true,
        headed: true,
        waitForSelector: ".detail.mileage, .details",
        settleMs: 4_000,
      }),
    ],
    notes: "Scorch /motor cards expose Year/Mileage after a public headed render.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "brent-mealin",
    displayName: "Brent Mealin",
    status: "confirmed",
    website: "https://www.brentmealin.com/",
    stockUrls: ["https://www.brentmealin.com/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Brent Mealin stock", "https://www.brentmealin.com/", "html-structured")],
    notes: "Research saw unrelated spam/casino content. Validate extracted records aggressively.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "budget-cars-isle-of-man",
    displayName: "Budget Cars Isle of Man",
    status: "confirmed",
    website: "https://www.budgetcars.im/",
    stockUrls: ["https://www.budgetcars.im/", "https://www.budgetcars.im/inventory"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source("stock", "Budget Cars stock", "https://www.budgetcars.im/", "html-structured"),
      source("inventory", "Budget inventory", "https://www.budgetcars.im/inventory", "html-structured", {
        preferBrowser: true,
      }),
    ],
    notes: "Trading as Bauto Limited. Homepage and /inventory expose Next inventory cards.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "bvs-vehicles",
    displayName: "BVS Vehicles",
    status: "confirmed",
    website: "https://bvsvehicles.com/",
    stockUrls: ["https://bvsvehicles.com/our-vehicles/"],
    platformHint: "Dragon2000",
    connectorKey: "dragon2000",
    groupKey: null,
    locations: ["Douglas"],
    sources: [
      source("used-cars", "BVS used cars", "https://bvsvehicles.com/our-vehicles/", "dragon2000", {
        preferBrowser: true,
      }),
    ],
    notes: "Dragon2000 public list at /our-vehicles/. Headed inspect captured /api/vehicles/instock.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "carshop",
    displayName: "Carshop",
    status: "confirmed",
    website: "https://carshop.co.im/",
    stockUrls: ["https://carshop.co.im/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Carshop latest stock", "https://carshop.co.im/", "html-structured")],
    notes: "Official site carshop.co.im. carshop.im cert does not match.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "cars-4-you",
    displayName: "Cars 4 You",
    status: "confirmed",
    website: "https://www.cars4u.im/",
    stockUrls: ["https://www.cars4u.im/cars"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: ["Ballasalla"],
    sources: [source("stock", "Cars 4 You stock", "https://www.cars4u.im/cars", "html-structured")],
    notes: "Official catalogue is cars4u.im/cars.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "dw-cars",
    displayName: "DW Cars",
    status: "confirmed",
    website: "https://www.dwcars.info/",
    stockUrls: ["https://www.dwcars.info/cars_new.html"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "DW Cars stock", "https://www.dwcars.info/cars_new.html", "html-structured")],
    notes: "Official stock list is dwcars.info/cars_new.html (car-view cards).",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "franklins",
    displayName: "Franklins",
    status: "confirmed",
    website: "https://www.franklins.co.im/",
    stockUrls: ["https://www.franklins.co.im/used/cars/port-erin/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source(
        "used-cars",
        "Franklins used cars",
        "https://www.franklins.co.im/used/cars/port-erin/",
        "html-structured",
      ),
    ],
    notes: "Official used list is franklins.co.im/used/cars/port-erin/ (list-box-wrapper cards).",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "im1-car-centre",
    displayName: "iM1 Car Centre",
    status: "confirmed",
    website: "https://www.im1carcentre.com/",
    stockUrls: ["https://www.im1carcentre.com/"],
    platformHint: "Fifty2one",
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source("used-cars", "iM1 used cars", "https://www.im1carcentre.com/", "html-structured", { required: false }),
    ],
    notes: "Homepage sends current stock to Facebook. No first-party inventory list.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "im8-vehicle-sales",
    displayName: "IM8 Vehicle Sales",
    status: "no_public_site",
    website: null,
    stockUrls: [],
    platformHint: null,
    connectorKey: "csv",
    groupKey: null,
    locations: ["Ramsey"],
    sources: [source("csv", "CSV/manual", null, "csv", { required: false })],
    notes: "Facebook/social presence only. No standalone website.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "ingear-car-sales",
    displayName: "Ingear Car Sales",
    status: "confirmed",
    website: "https://www.ingearcarsales.co.uk/",
    stockUrls: ["https://www.ingearcarsales.co.uk/"],
    platformHint: "Dealer Websites",
    connectorKey: "dealer-websites",
    groupKey: null,
    locations: ["Douglas"],
    sources: [
      source("used-cars", "Ingear used cars", "https://www.ingearcarsales.co.uk/", "dealer-websites"),
    ],
    notes: "Site identifies Dealer Websites as platform/provider.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "kingswood-honda",
    displayName: "Kingswood Honda",
    status: "confirmed",
    website: "https://www.kingswood-honda.com/",
    stockUrls: ["https://www.kingswood-honda.com/pre-owned/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: ["Douglas"],
    sources: [
      source("used-cars", "Kingswood used cars", "https://www.kingswood-honda.com/pre-owned/", "html-structured"),
    ],
    notes: "Franchise site. Prefer DMS export if scrape is incomplete.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "manx-car-store",
    displayName: "Manx Car Store",
    status: "confirmed",
    website: "https://www.manxcarstore.com/",
    stockUrls: ["https://www.manxcarstore.com/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Manx Car Store stock", "https://www.manxcarstore.com/", "html-structured")],
    notes: "Active into August 2026.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "manx-car-warehouse",
    displayName: "Manx Car Warehouse",
    status: "confirmed",
    website: "https://www.manxcarwarehouse.com/",
    stockUrls: ["https://www.manxcarwarehouse.com/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Manx Car Warehouse stock", "https://www.manxcarwarehouse.com/", "html-structured")],
    notes: "Inspect live source/feed.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "mike-hewison-autos",
    displayName: "Mike Hewison Autos",
    status: "confirmed",
    website: null,
    stockUrls: [],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Mike Hewison stock", null, "html-structured", { required: false })],
    notes: "Directory domain did not resolve on 2026-08-22. No first-party stock URL found.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "mikes-motors",
    displayName: "Mikes Motors",
    status: "confirmed",
    website: "https://www.mikesmotors.im/",
    stockUrls: ["https://www.mikesmotors.im/used-cars"],
    platformHint: "Click Dealer",
    connectorKey: "click-dealer",
    groupKey: null,
    locations: [],
    sources: [
      source("used-cars", "Mikes Motors used cars", "https://www.mikesmotors.im/used-cars", "click-dealer", {
        headed: true,
        waitForSelector: ".listing, .results-vehicleresults",
        settleMs: 6_000,
        maxPages: 5,
      }),
      source("used-vans", "Mikes Motors used vans", "https://www.mikesmotors.im/used-vans", "click-dealer", {
        headed: true,
        required: false,
        waitForSelector: ".listing, .results-vehicleresults",
        settleMs: 6_000,
        maxPages: 3,
      }),
      source("used-bikes", "Mikes Motors used bikes", "https://www.mikesmotors.im/used-bikes", "click-dealer", {
        headed: true,
        required: false,
        waitForSelector: ".listing, .results-vehicleresults",
        settleMs: 4_000,
      }),
    ],
    notes: "Click Dealer used list is /used-cars. Public headed Chromium reads the rendered results list.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "motorx",
    displayName: "MotorX",
    status: "confirmed",
    website: "https://www.motorx.im/",
    stockUrls: ["https://motorx.im/cars/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: ["Ramsey"],
    sources: [source("stock", "MotorX stock", "https://motorx.im/cars/", "html-structured")],
    notes: "Company 138613C. Public list is motorx.im/cars/ (cdinv-card markup).",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "ocean-motor-village",
    displayName: "Ocean Motor Village",
    status: "confirmed",
    website: "https://www.oceanmotorvillage.com/",
    stockUrls: [
      "https://www.oceanmotorvillage.com/search/",
      "https://www.oceanford.com/used-cars/ocean-ford/",
      "https://www.oceanford.com/transit-centre/used-vans/",
      "https://www.oceankia.com/used-cars/",
      "https://www.oceancitroen.com/used-cars/",
    ],
    platformHint: "NetDirector",
    connectorKey: "netdirector",
    groupKey: "ocean",
    locations: ["Ocean Ford", "Ocean Ford - Transit Centre", "Ocean KIA", "Ocean Citroën"],
    sources: [
      source("omv", "Ocean Motor Village", "https://www.oceanmotorvillage.com/search/", "netdirector", {
        required: false,
        dedicated: false,
      }),
      source("ocean-ford", "Ocean Ford", "https://www.oceanford.com/used-cars/ocean-ford/", "netdirector"),
      source(
        "transit-centre",
        "Ocean Ford - Transit Centre",
        "https://www.oceanford.com/transit-centre/used-vans/",
        "netdirector",
      ),
      source("ocean-kia", "Ocean KIA", "https://www.oceankia.com/used-cars/", "netdirector"),
      source("ocean-citroen", "Ocean Citroën", "https://www.oceancitroen.com/used-cars/", "netdirector", {
        required: false,
        notes: "Include if public stock exists; dealer-wide dedupe against other Ocean sources.",
      }),
    ],
    notes: "Bentley Isle of Man Ltd. Multiple NetDirector API generations. Exclude 4Hire and off-island stock in Ocean facade filters.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "paul-ridgway",
    displayName: "Paul Ridgway",
    status: "confirmed",
    website: "https://www.paulridgway.com/",
    stockUrls: ["https://www.paulridgway.com/"],
    platformHint: "iomwebdesign",
    connectorKey: "iomwebdesign",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Paul Ridgway stock", "https://www.paulridgway.com/", "iomwebdesign")],
    notes: "Share iomwebdesign connector with Phil Shaw only if inventory implementations match.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "phil-shaw-vehicles",
    displayName: "Phil Shaw Vehicles",
    status: "confirmed",
    website: "https://www.philshawvehicles.im/",
    stockUrls: ["https://www.philshawvehicles.im/our-latest-range/"],
    platformHint: "iomwebdesign",
    connectorKey: "iomwebdesign",
    groupKey: null,
    locations: [],
    sources: [
      source("stock", "Phil Shaw stock", "https://www.philshawvehicles.im/our-latest-range/", "html-structured"),
    ],
    notes: "Nicepage product cards on /our-latest-range/ include price, first registered year, and mileage.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "rex-motor-company",
    displayName: "Rex Motor Company",
    status: "confirmed",
    website: "https://www.rexmotorcompany.im/",
    stockUrls: ["https://www.rexmotorcompany.im/"],
    platformHint: "DotPerformance",
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source("stock", "Rex stock", "https://www.rexmotorcompany.im/", "html-structured"),
      source("sales", "Rex sales", "https://www.rexmotorcompany.im/sales", "html-structured", { required: false }),
      source("retail", "Rex retail", "https://www.rexmotorcompany.im/retail", "html-structured", { required: false }),
    ],
    notes: "Official site rexmotorcompany.im. /sales and /retail list current stock; year and miles are often on detail pages.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "select-car-sales",
    displayName: "Select Car Sales",
    status: "confirmed",
    website: "http://www.selectcarsales.co.im/",
    stockUrls: ["http://www.selectcarsales.co.im/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Select Car Sales stock", "http://www.selectcarsales.co.im/", "html-structured")],
    notes: "Official ASP.NET site selectcarsales.co.im. Homepage property-listing cards include price and mileage.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "skillannaylor-car-company",
    displayName: "SkillanNaylor Car Company",
    status: "confirmed",
    website: "https://sncc.im/",
    stockUrls: ["https://sncc.im/cars/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source("used-cars", "SkillanNaylor used cars", "https://sncc.im/cars/", "html-structured"),
    ],
    notes: "Official used list is sncc.im/cars/ (Car Dealer theme new-price cards).",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "swift-motors",
    displayName: "Swift Motors",
    status: "confirmed",
    website: "https://swiftmotors.net/",
    stockUrls: ["https://swiftmotors.net/used-vehicles/"],
    platformHint: "Codeweavers/Bluesky",
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source("used-cars", "Swift used vehicles", "https://swiftmotors.net/used-vehicles/", "html-structured", {
        maxPages: 4,
      }),
    ],
    notes: "Public list is /used-vehicles/ (bsk-vehicle-card markup) with page-2 pagination.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "td-car-centre",
    displayName: "TD Car Centre",
    status: "confirmed",
    website: "https://www.tdcar.im/",
    stockUrls: ["https://www.tdcar.im/inventory"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [
      source("stock", "TD Car Centre stock", "https://www.tdcar.im/inventory", "html-structured", {
        maxPages: 5,
      }),
    ],
    notes: "Public inventory is tdcar.im/inventory with SSR cards and ?page=2..5 pagination. Advertised count is on the listing heading.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "van-mossel-jacksons",
    displayName: "Van Mossel Jacksons",
    status: "confirmed",
    website: "https://www.jacksons.im/",
    stockUrls: ["https://www.vanmossel.im/jacksons"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: "van-mossel",
    locations: ["Isle of Man"],
    sources: [
      source(
        "used-cars",
        "Van Mossel Jacksons used cars",
        "https://www.vanmossel.im/jacksons",
        "html-structured",
      ),
    ],
    notes: "Live used hub is vanmossel.im/jacksons. Prefer group feed commercially.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "van-mossel-motor-mall",
    displayName: "Van Mossel Motor Mall",
    status: "confirmed",
    website: "https://www.motor-mall.im/",
    stockUrls: ["https://www.vanmossel.im/motormall"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: "van-mossel",
    locations: [],
    sources: [
      source(
        "used-cars",
        "Motor Mall used cars",
        "https://www.vanmossel.im/motormall",
        "html-structured",
      ),
    ],
    notes: "Live used hub is vanmossel.im/motormall. Dedup within this operation only.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "vehicles-im",
    displayName: "Vehicles.im",
    status: "confirmed",
    website: "http://www.vehicles.im/",
    stockUrls: [],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: ["Snugborough"],
    sources: [source("stock", "Vehicles.im stock", null, "html-structured", { required: false })],
    notes: "HTTP site redirects to Facebook. No first-party public stock list.",
    lastVerifiedAt: "2026-08-22",
  }),
  dealer({
    key: "mann-auto-car-sales",
    displayName: "Mann Auto Car Sales",
    status: "unverified",
    website: null,
    stockUrls: [],
    platformHint: null,
    connectorKey: "unknown",
    groupKey: null,
    locations: ["Snugborough"],
    sources: [source("unknown", "Unverified", null, "unknown", { required: false })],
    notes: "Directory presence only. Probe but keep unverified unless first-party stock is found.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "manx-motors",
    displayName: "Manx Motors",
    status: "unverified",
    website: null,
    stockUrls: [],
    platformHint: null,
    connectorKey: "unknown",
    groupKey: null,
    locations: ["Ballasalla"],
    sources: [source("unknown", "Unverified", null, "unknown", { required: false })],
    notes: "Directory presence at Balthane/Ballasalla. Keep unverified unless first-party evidence appears.",
    lastVerifiedAt: null,
  }),
  dealer({
    key: "pextray",
    displayName: "Pextray",
    status: "specialist_optional",
    website: "https://www.pextray.com/",
    stockUrls: ["https://www.pextray.com/"],
    platformHint: null,
    connectorKey: "html-structured",
    groupKey: null,
    locations: [],
    sources: [source("stock", "Pextray stock", "https://www.pextray.com/", "html-structured", { required: false })],
    notes: "Optional commercial/specialist prospect. Do not count as a core dealer.",
    lastVerifiedAt: null,
  }),
];

export function getDealer(key: string) {
  const dealerRecord = DEALER_REGISTRY.find((item) => item.key === key);
  if (!dealerRecord) throw new Error(`Unknown dealer: ${key}`);
  return dealerRecord;
}

export function listDealers(filter?: { includeOptional?: boolean; includeUnverified?: boolean }) {
  return DEALER_REGISTRY.filter((item) => {
    if (item.status === "specialist_optional" && !filter?.includeOptional) return false;
    if (item.status === "unverified" && !filter?.includeUnverified) return false;
    return true;
  });
}

export function confirmedDealersWithSites() {
  return DEALER_REGISTRY.filter((item) => item.status === "confirmed" && item.website);
}
