// Versioned against the production Auth shape read on 2026-10-05. No record data.
export const AUTH_EXPORT_SCHEMA = "itrader_sync_export";
export const AUTH_EXPORT_VERSION = "itrader-auth-export:v1";
export const AUTH_EXPORT_TABLES = ["users", "identities"] as const;
export type AuthExportTable = typeof AUTH_EXPORT_TABLES[number];
export const AUTH_EXPORT_COLUMNS = {
  users: [
    {"name":"instance_id","type":"uuid","generated":""},
    {"name":"id","type":"uuid","generated":""},
    {"name":"aud","type":"character varying(255)","generated":""},
    {"name":"role","type":"character varying(255)","generated":""},
    {"name":"email","type":"character varying(255)","generated":""},
    {"name":"encrypted_password","type":"character varying(255)","generated":""},
    {"name":"email_confirmed_at","type":"timestamp with time zone","generated":""},
    {"name":"invited_at","type":"timestamp with time zone","generated":""},
    {"name":"confirmation_token","type":"character varying(255)","generated":""},
    {"name":"confirmation_sent_at","type":"timestamp with time zone","generated":""},
    {"name":"recovery_token","type":"character varying(255)","generated":""},
    {"name":"recovery_sent_at","type":"timestamp with time zone","generated":""},
    {"name":"email_change_token_new","type":"character varying(255)","generated":""},
    {"name":"email_change","type":"character varying(255)","generated":""},
    {"name":"email_change_sent_at","type":"timestamp with time zone","generated":""},
    {"name":"last_sign_in_at","type":"timestamp with time zone","generated":""},
    {"name":"raw_app_meta_data","type":"jsonb","generated":""},
    {"name":"raw_user_meta_data","type":"jsonb","generated":""},
    {"name":"is_super_admin","type":"boolean","generated":""},
    {"name":"created_at","type":"timestamp with time zone","generated":""},
    {"name":"updated_at","type":"timestamp with time zone","generated":""},
    {"name":"phone","type":"text","generated":""},
    {"name":"phone_confirmed_at","type":"timestamp with time zone","generated":""},
    {"name":"phone_change","type":"text","generated":""},
    {"name":"phone_change_token","type":"character varying(255)","generated":""},
    {"name":"phone_change_sent_at","type":"timestamp with time zone","generated":""},
    {"name":"confirmed_at","type":"timestamp with time zone","generated":"s"},
    {"name":"email_change_token_current","type":"character varying(255)","generated":""},
    {"name":"email_change_confirm_status","type":"smallint","generated":""},
    {"name":"banned_until","type":"timestamp with time zone","generated":""},
    {"name":"reauthentication_token","type":"character varying(255)","generated":""},
    {"name":"reauthentication_sent_at","type":"timestamp with time zone","generated":""},
    {"name":"is_sso_user","type":"boolean","generated":""},
    {"name":"deleted_at","type":"timestamp with time zone","generated":""},
    {"name":"is_anonymous","type":"boolean","generated":""},
  ],
  identities: [
    {"name":"provider_id","type":"text","generated":""},
    {"name":"user_id","type":"uuid","generated":""},
    {"name":"identity_data","type":"jsonb","generated":""},
    {"name":"provider","type":"text","generated":""},
    {"name":"last_sign_in_at","type":"timestamp with time zone","generated":""},
    {"name":"created_at","type":"timestamp with time zone","generated":""},
    {"name":"updated_at","type":"timestamp with time zone","generated":""},
    {"name":"email","type":"text","generated":"s"},
    {"name":"id","type":"uuid","generated":""},
  ],
} as const;
